### ISSUE TITLE
Create scripts to manage versioning

### ISSUE THREAD

**Issue by infosec-alchemist** [iadgov/cti-stix-services#31]

**Comment by exceptionfactory** [comment]
Possible options include https://github.com/semantic-release/semantic-release and https://github.com/phuu/npm-release. Some utilities focus on NPM and Git tagging for single projects, ideally a solution would include support for incrementing version numbers across multiple projects.

**Comment by infosec-alchemist** [comment]
There also seems to be good connections between Dockerhub and Github that will do automated deployments.
