### ISSUE TITLE
Error when building docker-compose

### ISSUE THREAD

**Issue by infosec-alchemist** [iadgov/cti-stix-services#4]
I downloaded the latest, and I'm getting the following errors when running docker-compose

cti-stix-store    | npm info lifecycle cti-stix-store@0.2.0~prestart: cti-stix-store@0.2.0
cti-stix-store    | npm info lifecycle cti-stix-store@0.2.0~start: cti-stix-store@0.2.0
cti-stix-store    |
cti-stix-store    | > cti-stix-store@0.2.0 start /usr/share/cti-stix-store
cti-stix-store    | > node .
cti-stix-store    |
cti-stix-store    | module.js:457
cti-stix-store    |     throw err;
cti-stix-store    |     ^
cti-stix-store    |
cti-stix-store    | Error: Cannot find module 'loopback'

**Comment by infosec-alchemist** [comment]
I don't get this error when I run the container in the unfetter-discover compose.

**Comment by exceptionfactory** [comment]
Completed in Pull Request #5
